// flow-typed signature: 54586b266ad7ba605b08e455e5a02d67
// flow-typed version: <<STUB>>/eslint-config-adequate_v^1.1.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-adequate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-adequate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-adequate/rules/ecma' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/import' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/promise' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-adequate/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-adequate/index' {
  declare module.exports: $Exports<'eslint-config-adequate'>;
}
declare module 'eslint-config-adequate/index.js' {
  declare module.exports: $Exports<'eslint-config-adequate'>;
}
declare module 'eslint-config-adequate/rules/ecma.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/ecma'>;
}
declare module 'eslint-config-adequate/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/errors'>;
}
declare module 'eslint-config-adequate/rules/import.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/import'>;
}
declare module 'eslint-config-adequate/rules/index.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/index'>;
}
declare module 'eslint-config-adequate/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/node'>;
}
declare module 'eslint-config-adequate/rules/promise.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/promise'>;
}
declare module 'eslint-config-adequate/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/strict'>;
}
declare module 'eslint-config-adequate/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/style'>;
}
declare module 'eslint-config-adequate/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-adequate/rules/variables'>;
}
