// flow-typed signature: f35bc9272184f4dd646718a9dc7b17e1
// flow-typed version: <<STUB>>/estraverse_v^4.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'estraverse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'estraverse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'estraverse/estraverse' {
  declare module.exports: any;
}

declare module 'estraverse/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'estraverse/estraverse.js' {
  declare module.exports: $Exports<'estraverse/estraverse'>;
}
declare module 'estraverse/gulpfile.js' {
  declare module.exports: $Exports<'estraverse/gulpfile'>;
}
